### ISSUE TITLE
Starting bot

### ISSUE THREAD

**Issue by mgundle302** [tflaglor1/restock_monitor#1]
Hello - this seems like a nice little project and would like to get it started

I created .env - named it exactly as how the scripts shows "webhook-discord"

I ran NPM Install - NPM Start & I'm receiving this error:
**npm ERR! missing script: start**

Can you tell me what I might be doing wrong?

Thank you so much for your help

**Comment by tflaglor1** [comment]
Make sure the .env variable is all uppercase WEBHOOK_DISCORD and set it equal to your webhook URL. To start it use the command: node index.js
